#!/usr/bin/env python3

KILLTEAMS = [
    {'id': 'arbites', 'name': 'Adeptus Arbites'},
    {'id': 'custodes', 'name': 'Adeptus Custodes'},
    {'id': 'mechanicus', 'name': 'Adeptus Mechanicus'},
    {'id': 'sororitas', 'name': 'Adepta Sororitas'},
    {'id': 'cartographica', 'name': 'Astra Cartographica'},
    {'id': 'militarum', 'name': 'Astra Militarum'},
    {'id': 'grey_knights', 'name': 'Grey Knights'},
    {'id': 'navis', 'name': 'Navis Imperialis'},
    {'id': 'sm', 'name': 'Space Marines'},
    {'id': 'daemons', 'name': 'Chaos Daemons'},
    {'id': 'csm', 'name': 'Chaos Space Marines'},
    {'id': 'death_guard', 'name': 'Death Guard'},
    {'id': 'thousand_sons', 'name': 'Thousand Sons'},
    {'id': 'corsairs', 'name': 'Corsairs'},
    {'id': 'craftworlds', 'name': 'Craftworlds'},
    {'id': 'drukhari', 'name': 'Drukhari'},
    {'id': 'harlequins', 'name': 'Harlequins'},
    {'id': 'gene_cults', 'name': 'Genestealer Cults'},
    {'id': 'kroot', 'name': 'Kroot'},
    {'id': 'necrons', 'name': 'Necrons'},
    {'id': 'orks', 'name': 'Orks'},
    {'id': 'tau', 'name': 'T`au Empire'},
    {'id': 'tyranids', 'name': 'Tyranids'},
]

FIRETEAMS = [
    {'id': 'ecclesiarcy', 'name': 'Ecclesiarcy', 'killteam': 'sororitas'},
    {'id': 'novitiate', 'name': 'Novitiate', 'killteam': 'sororitas'},
    {'id': 'exactionsquad', 'name': 'Exaction Squad', 'killteam': 'arbites'},
    {'id': 'talons', 'name': 'Talons of the Emperor', 'killteam': 'custodes'},
    {'id': 'hunterclade', 'name': 'Hunter Clade', 'killteam': 'mechanicus'},
    {'id': 'starstrider', 'name': 'Elucidian Starstrider', 'killteam': 'cartographica'},
    {'id': 'imperialguard', 'name': 'Imperial Guard', 'killteam': 'militarum'},
    {'id': 'karskin', 'name': 'Karskin', 'killteam': 'militarum'},
    {'id': 'veteranguard', 'name': 'Veteran Guardsman', 'killteam': 'militarum'},
    {'id': 'breachers', 'name': 'Imperial Navy Breacher', 'killteam': 'navis'},
    {'id': 'intercession', 'name': 'Intercession Squad', 'killteam': 'sm'},
    {'id': 'phobosstrike', 'name': 'Phobos Strike Team', 'killteam': 'sm'},
    {'id': 'spacemarines', 'name': 'Space Marines', 'killteam': 'sm'},
    {'id': 'chaosdaemons', 'name': 'Chaos Daemons', 'killteam': 'daemons'},
    {'id': 'gellerpox', 'name': 'Gellerpox Infected', 'killteam': 'daemons'},
    {'id': 'blooded', 'name': 'Blooded', 'killteam': 'csm'},
    {'id': 'legionary', 'name': 'Legionary', 'killteam': 'csm'},
    {'id': 'traitors', 'name': 'Traitor Space Marines', 'killteam': 'csm'},
    {'id': 'deathguard', 'name': 'Death Guard', 'killteam': 'death_guard'},
    {'id': 'warpcoven', 'name': 'Warpcoven', 'killteam': 'thousand_sons'},
    {'id': 'corsairs', 'name': 'Corsair Voidscarred', 'killteam': 'corsairs'},
    {'id': 'craftworld', 'name': 'Craftworld', 'killteam': 'craftworld'},
    {'id': 'commorrite', 'name': 'Commorrite', 'killteam': 'drukhari'},
    {'id': 'archon', 'name': 'Hand of Archon', 'killteam': 'drukhari'},
    {'id': 'troupe', 'name': 'Void-dancer Troupe', 'killteam': 'harlequins'},
    {'id': 'brood', 'name': 'Brood Coven', 'killteam': 'gene_cults'},
    {'id': 'wyrmblade', 'name': 'Wyrmblade', 'killteam': 'gene_cults'},
    {'id': 'kindband', 'name': 'Farstalker Kindband', 'killteam': 'kroot'},
    {'id': 'hierotek', 'name': 'Hierotek Circle', 'killteam': 'necrons'},
    {'id': 'tomb', 'name': 'Tomb World', 'killteam': 'necrons'},
    {'id': 'greenskin', 'name': 'Greenskin', 'killteam': 'orks'},
    {'id': 'kommando', 'name': 'Kommando', 'killteam': 'orks'},
    {'id': 'mercenary', 'name': 'Cadre Mercenary', 'killteam': 'tau'},
    {'id': 'hunter', 'name': 'Hunter Cadre', 'killteam': 'tau'},
    {'id': 'pathfinder', 'name': 'Pathfinder', 'killteam': 'tau'},
    {'id': 'hivefleet', 'name': 'Hive Fleet', 'killteam': 'tyranids'},
]

UNITS = [
    {'id': 'sob_warrior', 'name': 'Battle Sister Warrior', 'fireteam': 'ecclesiarcy', 'weapons': ['boltgun', 'gunbutt']},
    {'id': 'sob_icon_bearer', 'name': 'Battle Sister Icon Bearer', 'fireteam': 'ecclesiarcy', 'weapons': ['boltgun', 'gunbutt']},
    {'id': 'sob_gunner', 'name': 'Battle Sister Gunner', 'fireteam': 'ecclesiarcy', 'weapons':['meltagun', 'gunbutt']},
    {'id': 'sob_gunner', 'name': 'Battle Sister Gunner', 'fireteam': 'ecclesiarcy', 'weapons':['min_flamer', 'gunbutt']},
    {'id': 'sob_gunner', 'name': 'Battle Sister Gunner', 'fireteam': 'ecclesiarcy', 'weapons':['stormbolter', 'gunbutt']},
    {'id': 'sob_heavy_gunner', 'name': 'Battle Sister Heavy Gunner', 'fireteam': 'ecclesiarcy', 'weapons':['heavy_bolter', 'gunbutt']},
    {'id': 'sob_heavy_gunner', 'name': 'Battle Sister Heavy Gunner', 'fireteam': 'ecclesiarcy', 'weapons':['min_heavy_flamer', 'gunbutt']},
    {'id': 'sob_repentia', 'name': 'Sister Repentia', 'fireteam': 'ecclesiarcy', 'weapons': ['pen_eviscerator']},
    {'id': 'sob_repentia_sup', 'name': 'Repentia Superior', 'fireteam': 'ecclesiarcy', 'weapons': ['neural_whips']},
    {'id': 'sob_arco_flag', 'name': 'Arco-Flaggelant', 'fireteam': 'ecclesiarcy', 'weapons': ['arco_flails']},
    {'id': 'sob_superior', 'name': 'Sister Superior', 'fireteam' : 'ecclesiarcy', 'weapons': ['boltpistol', 'gunbutt']},
    {'id': 'sob_superior', 'name': 'Sister Superior', 'fireteam' : 'ecclesiarcy', 'weapons': ['plasmapistol', 'gunbutt']},
    {'id': 'sob_superior', 'name': 'Sister Superior', 'fireteam' : 'ecclesiarcy', 'weapons': ['infernopistol', 'gunbutt']},
    {'id': 'sob_superior', 'name': 'Sister Superior', 'fireteam' : 'ecclesiarcy', 'weapons': ['boltgun', 'gunbutt']},
    {'id': 'sob_superior', 'name': 'Sister Superior', 'fireteam' : 'ecclesiarcy', 'weapons': ['combi_melta', 'gunbutt']},
    {'id': 'sob_superior', 'name': 'Sister Superior', 'fireteam' : 'ecclesiarcy', 'weapons': ['combi_plasma', 'gunbutt']},
]

WEAPONS = [
    {'id': 'gunbutt', 'name': 'Gun Butt', 'type':'melee'},
    {'id': 'boltgun', 'name': 'Boltgun', 'type':'ranged'},
    {'id': 'meltagun', 'name': 'Meltagun', 'type':'ranged'},
    {'id': 'min_flamer', 'name': 'Ministorum Flamer', 'type':'ranged'},
    {'id': 'stormbolter', 'name': 'Stormbolter', 'type':'ranged'},
    {'id': 'heavy_bolter', 'name': 'Heavy Bolter', 'type':'ranged'},
    {'id': 'min_heavy_flamer', 'name': 'Ministorum Heavy Flamer', 'type':'ranged'},
    {'id': 'pen_eviscerator', 'name': 'Penitent Eviscerator', 'type':'melee'},
    {'id': 'neural_whips', 'name': 'Neural Whips', 'type': 'combo'},
    {'id': 'arco_flails', 'name': 'Arco Flails', 'type': 'melee'},
    {'id': 'boltpistol', 'name': 'Bolt Pistol', 'type': 'ranged'},
    {'id': 'plasmapistol', 'name': 'Plasma Pistol', 'type': 'ranged'},
    {'id': 'infernopistol', 'name': 'Inferno Pistol', 'type': 'ranged'},
    {'id': 'combi_melta', 'name': 'Combi-Melta', 'type': 'ranged'},
    {'id': 'combi_plasma', 'name': 'Combi-Plasma', 'type': 'ranged'},
]
